<?php

/**
 * @file
 * Webservice mockup of Open Agency
 */
function bibdk_openorder_webservice_mockup_menu() {
  $items['bibdk_openorder_webservice'] = array(
    'page callback' => 'bibdk_openorder_webservice_mockup_request',
    'access callback' => 'bibdk_openorder_webservice_mockup_access',
  );
  $items['bibdk_openorder_mockup'] = array(
    'page callback' => 'bibdk_openorder_webservice_mockup_request',
    'access callback' => 'bibdk_openorder_webservice_mockup_access',
  );

  return $items;
}

function bibdk_openorder_webservice_mockup_form($form,$form_state){
  $form['checkOrderPolicy'] = array(
    '#type' => 'fieldset',
    '#title' => 'Check order policy request',
    '#description' => 'Default values is a good request, to test a bad request; make some changes',
  );
   $form['checkOrderPolicy']  = array(
    '#method'=>'post',
    'submit'=>array(
      '#type'=>'submit',
      '#value'=>'test me',
    ),
    'pickupAgencyId'=>array(
      '#title' => 'pickupAgencyId',
      '#type'=>'textfield',
      '#default_value' => '715700',
    ),
    'pid' => array(
      '#title' => 'pid',
      '#type' => 'textfield',
      '#default_value' => '870970-basis:28794932',
    ),
  );

  return $form;
}

/**
 * Faking the request and returns result.
 * @return String json
 */
function bibdk_openorder_webservice_mockup_request() {
  $path = drupal_get_path('module', 'bibdk_openorder_webservice_mockup');
  //$data = file_get_contents('php://input');
  $data = $_POST;

  if( $data ) {
    // @TODO; do something here
    echo 'TESTHEST';
    print_r($data);
  }
  else {
    echo 'welcome to bibdk_openorder_webservice mockup</br>';
    echo drupal_render(drupal_get_form('bibdk_openorder_webservice_mockup_form'));
  }
}


/**
 * Parsing the request into a xml object
 * @param type request from ting-client
 * @return \SimpleXMLElement
 */
function bibdk_openorder_webservice_mockup_parse_xml($soap){
  $pattern = "/:?SOAP-ENV:?/";
  $replace = '';
  $xml = preg_replace($pattern, $replace, $soap);

  $envelope = new SimpleXMLElement($xml);
  return $envelope;
}

function bibdk_openorder_webservice_mockup_access() {
  return TRUE;
}
