<?php
/**
 * do a checkOrderPolicyRequest
 **/
function bibdk_openorder_do_checkOrderPolicy($pickupAgencyId,$pid){
  $params = _bibdk_openorder_set_fixed_parameters();
  $params['action'] = 'checkOrderPolicyRequest';

  // testing
  $pickupAgencyId = '715700';
  $pid = '870970-basis:28794932';

  $params['pickUpAgencyId'] = $pickupAgencyId;
  $params['pid'] = $pid;
  
  $client = new ting_client_class();
  $response = $client->do_openorder($params);
  return $response;
}

/**
 * parameters common for all request
 **/
function _bibdk_openorder_set_fixed_parameters(){
  $authentication = array();
  $authentication['groupIdAut'] = variable_get('bibdk_openorder_groupIdAut');
  $authentication['passwordAut'] = variable_get('bibdk_openorder_passwordAut');
  $authentication['userIdAut'] = variable_get('bibdk_openorder_userIdAut');
  $params['authentication'] = $authentication;

  $params['serviceRequester'] = variable_get('bibdk_openorder_serviceRequester');

  return $params;
}

/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 **/
function bibdk_openorder_ting_client_webservice () {
  return array('openorder' => 'bibdk_openorder_url',);
}

/**
 * Implements hook_form_FORM_ID_alter (ting_client_admin_webservices_settings)
 * add field to webservice client settings
 * @url to openorder
  **/
function bibdk_openorder_form_ting_client_admin_webservices_settings_alter (&$form,&$form_state) {
  $form['openorder'] = array(
    '#type' => 'fieldset',
    '#title' => t('Openorder settings'),
    '#description' => t('Setting for openorder webservice'),
    '#weight'=>-2,
  );

  $form['openorder']['bibdk_openorder_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Openorder URL'),
    '#description' => t('URL to openorder e.g. http://guesstimate.dbc.dk/~fvs/OpenLibrary/OpenOrder/trunk/server.php/'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_openorder_url', FALSE),
  );

  $form['openorder']['bibdk_openorder_groupIdAut'] = array(
    '#type' => 'textfield',
    '#title' => t('groupID authentication'),
    '#description' => t('groupIdAut for openorder e.g. 010100'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_openorder_groupIdAut', FALSE),
  );

  $form['openorder']['bibdk_openorder_passwordAut'] = array(
    '#type' => 'textfield',
    '#title' => t('password authentication'),
    '#description' => t('passwordAut for openorder e.g. 20Koster'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_openorder_passwordAut', FALSE),
  );

  $form['openorder']['bibdk_openorder_userIdAut'] = array(
    '#type' => 'textfield',
    '#title' => t('Userid authentication'),
    '#description' => t('userIdAut for openorder e.g. netpunkt'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_openorder_userIdAut', FALSE),
  );

   $form['openorder']['bibdk_openorder_serviceRequester'] = array(
    '#type' => 'textfield',
    '#title' => t('Servicerequester'),
    '#description' => t('Servicerequester for openorder e.g. 190101'),
    '#required' => TRUE,
    '#default_value' => variable_get('bibdk_openorder_serviceRequester', FALSE),
  );
}
